name: PR Test

on:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set Environment Variables
        run: |
          # Set environment variables from GitHub environment to runtime environment
          foreach ($env in (Get-ChildItem env:)) {
            echo "$($env.Name)=$($env.Value)" >> $env:GITHUB_ENV
          }
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest test
